### ISSUE TITLE
failed to parse response body.

### ISSUE THREAD

**Issue by beshoo** [WAppAI/assistant#223]
```

Loading WhatsApp Web... 0%
Loading WhatsApp Web... 100%
Authenticated
WhatsApp Web ready
Scheduled 0 reminders.
Bot is ready
12:18:47 [Bashar Al Masri->Bashar Al Masri@dm]: Hi
Error: /turing/conversation/create: failed to parse response body.

    at BingAIClient.createNewConversation (file:///F:/Whatsapp/bot/node_modules/.pnpm/github.com+Luisotee+node-chatgpt-api@4658463e178e0acd1d7f4bc6635b4104068972b7_uzhlc2j4vkdkeaukqhs5oq2dti/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:126:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BingAIClient.sendMessage (file:///F:/Whatsapp/bot/node_modules/.pnpm/github.com+Luisotee+node-chatgpt-api@4658463e178e0acd1d7f4bc6635b4104068972b7_uzhlc2j4vkdkeaukqhs5oq2dti/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:376:51)
    at async generateCompletionFor (file:///F:/Whatsapp/bot/src/handlers/completion.ts:143:18)
    at async getCompletionFor (file:///F:/Whatsapp/bot/src/handlers/completion.ts:69:22)
    at async handleMessage (file:///F:/Whatsapp/bot/src/handlers/message/index.ts:26:24)
12:18:51 [Bashar Al Masri->Bashar Al Masri@dm]: Error: /turing/conversation/create: failed to parse response body.

```

**Comment by beshoo** [comment]
VPN PROBLEM

**Comment by ElliotBadinger** [comment]
Hi
What do you mean it's a VPN problem? and how do I fix the issue.
