### ISSUE TITLE
Sydney crashes when you say it to draw something.

### ISSUE THREAD

**Issue by choudhryfrompak** [WAppAI/assistant#226]
![WhatsApp Image 2023-11-19 at 9 33 44 PM](https://github.com/WAppAI/assistant/assets/129526340/7668cf00-2425-4a03-b320-dc3d77abc363)

**As you can see this screenshot when i asked the chatbot to draw something it crashes it shows this error in the terminal.** 

`21:32:12 [CHOUDHRY❤️->undefined@dm]: draw a lion
file:///home/odin/assistant/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:610
                            bicIframe = this.bic.genImageIframeSsr(
                                                 ^

TypeError: Cannot read properties of undefined (reading 'genImageIframeSsr')
    at WebSocket.<anonymous> (file:///home/odin/assistant/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:610:50)
    at WebSocket.emit (node:events:526:35)
    at Receiver.receiverOnMessage (/home/odin/assistant/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:514:28)
    at Receiver.dataMessage (/home/odin/assistant/node_modules/ws/lib/receiver.js:560:14)
    at Receiver.getData (/home/odin/assistant/node_modules/ws/lib/receiver.js:478:17)
    at Receiver.startLoop (/home/odin/assistant/node_modules/ws/lib/receiver.js:167:22)
    at Receiver._write (/home/odin/assistant/node_modules/ws/lib/receiver.js:93:10)
    at writeOrBuffer (node:internal/streams/writable:447:12)
    at _write (node:internal/streams/writable:389:10)
    at Writable.write (node:internal/streams/writable:393:10)
    at TLSSocket.socketOnData (/home/odin/assistant/node_modules/ws/lib/websocket.js:1286:35)
    at TLSSocket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
`

** I think we can use this as a feature we can just use to handle this message type to send the output image in the chat. or we can handle this message to ignore  keywords like DRAW or IMAGINE**
_As you can see here too in usual bing it outputs an image in case we use keywords like that_

![image](https://github.com/WAppAI/assistant/assets/129526340/64792c2c-c4b5-4a02-bf3c-c0b72a091bd7)

**Comment by choudhryfrompak** [comment]
i would highly recommend to use it as a additional feature **IMAGE GENERATION**

If you need any help do reach me out at choudhry@pacgpt.chat

**Comment by Luisotee** [comment]
Currently it's not supporting the image generation feature, I am probably gonna add it sometime in the future but have no ETA.

**Comment by choudhryfrompak** [comment]
so you should handle this error then .. there is a great possibility that users are gonna try those keywords ... you can refine the input prompt like you do for the output .

**Comment by Luisotee** [comment]
Should properly display a message saying bing cannot draw pictures as of #268
