### ISSUE TITLE
Cannot perform transcription, permission error.

### ISSUE THREAD

**Issue by estilodevida** [WAppAI/assistant#250]
Error executing Whisper: Error: Command failed: "/Users/devopt/Documents/IA-software/assistant/whisper/main" -m "/Users/devopt/Documents/IA-software/assistant/whisper/models/ggml-model-whisper-base.bin" -f "/var/folders/zh/2d746fqj511d8__4d1h7xjr80000gn/T/62c57b26-7404-47f3-80ed-4fc80b8c4cf5.wav" -l "es" -nt
/bin/sh: /Users/devopt/Documents/IA-software/assistant/whisper/main: Permission denied

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at handleAudioMessageWithWhisperLocal (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/audio-message/whisper-local.ts:12:31)
    at handleAudioMessage (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/audio-message/index.ts:22:38)
    at async generateCompletionWithBing (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/llm-models/generate-completion-with-bing.ts:21:32)
    at async getCompletionWithBing (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/llm-models/completion-bing.ts:39:24)
    at async handleMessage (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/message/index.ts:19:32)
    at async Client.<anonymous> (file:///Users/devopt/Documents/IA-software/assistant/src/clients/whatsapp.ts:68:16) {
  status: 126,
  signal: null,
  output: [
    null,
    '',
    '/bin/sh: /Users/devopt/Documents/IA-software/assistant/whisper/main: Permission denied\n'
  ],
  pid: 34020,
  stdout: '',
  stderr: '/bin/sh: /Users/devopt/Documents/IA-software/assistant/whisper/main: Permission denied\n'
}
Error: Error executing Whisper
    at handleAudioMessageWithWhisperLocal (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/audio-message/whisper-local.ts:20:15)
    at handleAudioMessage (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/audio-message/index.ts:22:38)
    at async generateCompletionWithBing (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/llm-models/generate-completion-with-bing.ts:21:32)
    at async getCompletionWithBing (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/llm-models/completion-bing.ts:39:24)
    at async handleMessage (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/message/index.ts:19:32)
    at async Client.<anonymous> (file:///Users/devopt/Documents/IA-software/assistant/src/clients/whatsapp.ts:68:16)
Error: Error transcribing audio
    at handleAudioMessage (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/audio-message/index.ts:26:19)
    at async generateCompletionWithBing (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/llm-models/generate-completion-with-bing.ts:21:32)
    at async getCompletionWithBing (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/llm-models/completion-bing.ts:39:24)
    at async handleMessage (file:///Users/devopt/Documents/IA-software/assistant/src/handlers/message/index.ts:19:32)
    at async Client.<anonymous> (file:///Users/devopt/Documents/IA-software/assistant/src/clients/whatsapp.ts:68:16)

**Comment by Luisotee** [comment]
Is there any model inside `whisper/models` with the name of ggml-model-whisper-base.bin?

**Comment by Luisotee** [comment]
Should be fixed with #267
