### ISSUE TITLE
Jailbreak terminates program when turned on

### ISSUE THREAD

**Issue by ElliotBadinger** [WAppAI/assistant#274]
When I tried to set jailbreak to on the program just shut down printing this: `PrismaClientKnownRequestError:
Invalid `prisma.bingConversation.update()` invocation:

An operation failed because it depends on one or more records that were required but not found. Record to update not found.
    at wn.handleRequestError (/home/brainstein/git/assistant/node_modules/.pnpm/@prisma+client@5.3.1_prisma@5.3.1/node_modules/@prisma/client/runtime/library.js:123:6730)
    at wn.handleAndLogRequestError (/home/brainstein/git/assistant/node_modules/.pnpm/@prisma+client@5.3.1_prisma@5.3.1/node_modules/@prisma/client/runtime/library.js:123:6119)
    at wn.request (/home/brainstein/git/assistant/node_modules/.pnpm/@prisma+client@5.3.1_prisma@5.3.1/node_modules/@prisma/client/runtime/library.js:123:5839)
    at async l (/home/brainstein/git/assistant/node_modules/.pnpm/@prisma+client@5.3.1_prisma@5.3.1/node_modules/@prisma/client/runtime/library.js:128:9763)
    at async setChatJailbroken (file:///home/brainstein/git/assistant/src/handlers/command/jailbreak.ts:8:5)
    at async handleJailbreak (file:///home/brainstein/git/assistant/src/handlers/command/jailbreak.ts:40:13)
    at async handleCommand (file:///home/brainstein/git/assistant/src/handlers/command/index.ts:39:21)
    at async Client.<anonymous> (file:///home/brainstein/git/assistant/src/clients/whatsapp.ts:66:16) {
  code: 'P2025',
  clientVersion: '5.3.1',
  meta: { cause: 'Record to update not found.' }
}

Node.js v20.10.0
`

The bing cookie was set correctly as I could talk to the LLM model without jailbreak, but as the other thread mentioned, Bing forgets previous messages with every new message sent.

**Comment by Luisotee** [comment]
Try to do a `pnpm build`, dont forget to press Y when requested

**Comment by ElliotBadinger** [comment]
Restarting the program seemed to fix the issue
