### ISSUE TITLE
Error: Evaluation failed: Error: Reactions send Error

### ISSUE THREAD

**Issue by GreenerX** [WAppAI/assistant#289]
I'm getting this error after scanning the QR.
Node version 18.15.0

pnpm start --inspect

> whatsapp-ai-assistant@2.6.0 start /Users/amir/Desktop/AI Stuff/assistant
> ts-node src/index.ts "--inspect"

BING_COOKIES not provided. You will not be able to use the Bing model.
 ▄▄▄▄▄▄▄  ▄▄▄ ▄  ▄▄ ▄▄  ▄    ▄▄▄▄ ▄  ▄    ▄▄  ▄  ▄▄ ▄▄ ▄▄▄▄▄▄▄
 █ ▄▄▄ █ ▄▀ ▄ ▀▀▄█▀█▀▀█▀█▄▄ ▀█▄█▄  █▀▀▄█▀▄▄▀▀▀ █▄▀▀▄██ █ ▄▄▄ █
 █ ███ █ ██ █▀██    ▀█▄▄▄ ▀  ▄▄█▄▄▀██▀▄█▄ ▄ █▄█  ▀▄█▄▀ █ ███ █
 █▄▄▄▄▄█ █ █▀█▀█▀▄▀█ █▀▄ █ █▀█ ▄ █▀▄▀▄ ▄ █ █ ▄ █ ▄▀█ ▄ █▄▄▄▄▄█
 ▄ ▄▄▄▄▄ ▀ ███ ▀      ▄   ▀▀▄█▄▄▄█ ▄█▄▄▀ ▀▄█▄ █▄▀▄█ ▀█ ▄▄▄▄▄
   ▀▄  ▄▀▀▀▀▄█ ▀ ▀██▄     ▀█ ▄███▀▄▄▄▀█ █▄▀█ ▀▀▄█▄▀▄▄▄▄▀█▀█▀██
  █▄█▀▀▄ ▀████▀█ ▀ ▀▀██▄▄▄█  ▄▀█▀▀ ▄▄█▀   █▄▄▀▀ ▀▄█  ▀▄ █ ▀▄▄▀
 █▄█▄█ ▄▄ ▄ ▄▄▄▄▀  ▄▄    █ ▀██▀█▀▀  ▄█▀   ▀▀██  ▀█▀  ▄▀▀▄▀█▄▀▄
 ▄ ▄█ ▄▄▀█▀ █ ▀ ▄ █▀ ▀█▀▀▄█▀▀ ▀▀██▄▀▀█ ▄▄   ▀ ▄▄ ▄  ▀██▄▄▀▄ ██
   ▀▀▄█▄▄▀  █▀▀▀▀█▄▄█ █▄ ▄ ▀██▄▀▀▀▄ ▀█▀ ▄ ▀█▀ ▀▄█▀█ ▀ ██ ▄█▄▀▄
 ▄▀▀█ ▄▄▄▄  █   ▀ █ ▀▄▀█ ▄▀ ▄▄█▀██▄▄▄▄▄█ ▀▄█ ▀▀ █▄ ▄▀█ ▀▄ ▄ ▀
 ▀▄  ▀█▄▀▄▀█ ▄ ▄▀█ ▀██ ██▀▀ ▀▀▀ █▀▄▄▄██▄▀▀█▀█▄▀▄▄▀█▄▄▄▀▀  ▀ ██
 ▄█▀▀ █▄▄▄▀▀ ▄█  ▄█▀█▀▀▄▄██▀▀ ▀▄█ ▀  ▄▄ █▀▄█▄ ▀ ▄█▀▄▄█▀▀ ▀▄▄ ▀
 █▀ █▀▀▄█▀▀▄   ██▄▄▀█ █▄▄█  ▀▄█▄▄▄▀ █ ▄  ▄▄█▀▀█  █▄▄  ███▀ ▄▄▄
 ▀▀ ▀█▄▄▄▄█ ██▀ █▄█ ▄▄▄▀ ▀█  ▄██▄█▄█ ▄ ▄▀ ▀▄▀▀█▀▄▄ ██▄██▄▄▀▄ █
 ▀ ▄▀█ ▄ █▄▄█▀ ▄▄▀█▀█  █▀▀▀▀ █ ▄ █▄▄█▀█▄  ██▀ ▄  █▀  █ ▄ █▄ ▄▄
 ▄█ ▄█▄▄▄█▄▀▄█▄██▄▀▄█▄  ▀▀▄▀██▄▄▄██ ██ ▄▀ ▄ ▄ ██▄▄█▄▀█▄▄▄█  █▀
 ▄█ ▀▀█▄▀   ▀ ▄█ ▀▀ ▄██▀██ ▄▄  ▀██▄▄▀█▀▄▀▄▄▀▄  ▄▄█▄▄   █▀▄▀█▄█
 ▀ █▄▀▀▄▀ ▄ ▄▀ █ ▀▄ ▄▄▀ █▀▄ ▀█▀█ ▄  ▄▀▄█▀▄▄▀▄▄ ▄▀▄▄▀█▀▀ ▄▀▄ ▄▀
 ▄██▄█▀▄▀  ▀▄██  █▄    ▀▄█▄▄██▀▄ ▄▄▄▄ █▄▀█▀█▄█▄ █▄█ ▀ ▄██▄█ █▀
 ▄▄█▀ ▄▄█▄▀█  ██▀ ▄█▄ █▄ █▄█▀▀▀▄▄ ▄▄▄▄▀▄▀▀  ▀▀█ ▄▄ ▄██████▄▄ █
 ▄▄▄ █▀▄▀▄▀     ▄▀▄ █▄ ▄▀  ▄▄█ ▄ ▀  █ ▄▄▀ ▀██ ▄ █▀▀▄█ ▄▄▄▄ ▄█▄
 ▄▀▀██▄▄▀▀█▄  ▀▄▄██ █ █ ▀ █ █ ███▄▄█▄▄▀█▄▀▀ ▄ ▄███ ▄██▄ █▄▄▄▄▄
   ▀  ▀▄ █▄▀ █▀▀▀▄▀▄▄▀▄▀█▀ ▄▀▀ █ ▀▄▀▄▄▀▀▄ ▀▄  ▄▀▀▄▀▄▀▄▄▄▀▄ ▄▀▄
 ▀█▄█ █▄ ▀ ▀▀██▀▀▀██▀▄▀█▀▀█  ▀▀██▄▀▄▀▄     ▄▄ ▄ ▀▄▄▀▄█▀█▄▄▄ ▀▄
 ▀ ▄███▄ ▀ ▄ ▀█▄▀ █▄▄█▄ ██▀▀████▄ ▀▄█▀█ ▀▀▄▀▀█   ▄█▄█  ▄▀▄▄ ▄▄
 ███▄▀ ▄▄▄▀█ ▄█ █▀▄▀▀ █▄█▀▄▀▀█▄▄▄▄▀▀▀▄█▄▀▀ ██   ▄▄▄▄▄▄█▄▄▄▀▄█▄
 ▄▄▄▄▄▄▄ ▀▀▄█▀▄█▄█      ███▄▀█ ▄ ██▄▄█▄▄▀ ▀▀ ██▄  ▀ ▀█ ▄ █ ▀▄█
 █ ▄▄▄ █ █▄▀ ▀▄▀▄ ▀▀ ▄▄  ██ ▄█▄▄▄███▀█▀ ▄ ▀▀▀  █▄▄ ▀▄█▄▄▄█ ▄▀█
 █ ███ █ █▀▀▄  ▀█▀▄▀  ▄ █▀▀ ▄█▄▀▀  ▄▀██▄▄ ██▀  ▄█▀▀▄  ▄██▀▄▄ █
 █▄▄▄▄▄█ ▄▄▀▄▀ ▄▀▄▄▄▄ ▀ █▄▀ ▀▀▄██▀▀▀ ▄▀▄   ▀▄ █▄▄▄ ▀▄ █▀▀▄▄ ▄█
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

Loading WhatsApp Web... 0%
Loading WhatsApp Web... 100%
Authenticated
WhatsApp Web ready
Scheduled 0 reminders.
Bot is ready
Error: Evaluation failed: Error: Reactions send Error
    at new Error (<anonymous>:5:31)
    at e (https://web.whatsapp.com/:2:4914)
    at https://web.whatsapp.com/main.3c0856caedc043ca212c.js:5:1038718
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~app.6bd0798bf8d46303b447.js:2:66487)
    at s (https://web.whatsapp.com/vendor1~app.6bd0798bf8d46303b447.js:2:66698)
    at ExecutionContext._evaluateInternal (/Users/amir/Desktop/AI Stuff/assistant/node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/amir/Desktop/AI Stuff/assistant/node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at async Message.react (/Users/amir/Desktop/AI Stuff/assistant/node_modules/.pnpm/whatsapp-web.js@1.23.1-alpha.5/node_modules/whatsapp-web.js/src/structures/Message.js:416:9)
    at async react (file:///Users/amir/Desktop/AI%20Stuff/assistant/src/handlers/reactions.ts:20:7)
    at async workingOn (file:///Users/amir/Desktop/AI%20Stuff/assistant/src/helpers/message.ts:17:3)
    at async setStatusFor (file:///Users/amir/Desktop/AI%20Stuff/assistant/src/helpers/message.ts:32:7)
    at async handleMessage (file:///Users/amir/Desktop/AI%20Stuff/assistant/src/handlers/message/index.ts:23:3)
    at async Client.<anonymous> (file:///Users/amir/Desktop/AI%20Stuff/assistant/src/clients/whatsapp.ts:89:12)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by Luisotee** [comment]
I couldnt replicate it here, did you do anything to make this warning appear? Is the whatsapp account the same that you use normally?
