### ISSUE TITLE
Log Errors after connecting the QR Code

### ISSUE THREAD

**Issue by mkagit** [WAppAI/assistant#314]
`{"level":30,"time":1733247975654,"pid":364,"hostname":"e784456ae14512","name":"regular_low","error":"Error: failed to find key \"ABBBAJDE\" to decode patch\n    at decodeSyncdPatch (/usr/src/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_link-preview-js@3.0.12_encoding@0.1.13__qrcode-terminal@0.12.0/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:203:19)\n    at async decodePatches (/usr/src/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_link-preview-js@3.0.12_encoding@0.1.13__qrcode-terminal@0.12.0/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:320:30)\n    at async /usr/src/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_link-preview-js@3.0.12_encoding@0.1.13__qrcode-terminal@0.12.0/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:425:70\n    at async Object.transaction (/usr/src/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_link-preview-js@3.0.12_encoding@0.1.13__qrcode-terminal@0.12.0/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26)\n    at async /usr/src/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_link-preview-js@3.0.12_encoding@0.1.13__qrcode-terminal@0.12.0/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:361:9\n    at async /usr/src/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_link-preview-js@3.0.12_encoding@0.1.13__qrcode-terminal@0.12.0/node_modules/@whiskeysockets/baileys/lib/Utils/event-buffer.js:105:36\n    at async processNotification (/usr/src/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_link-preview-js@3.0.12_encoding@0.1.13__qrcode-terminal@0.12.0/node_modules/@whiskeysockets/baileys/lib/Socket/messages-recv.js:316:21)\n    at async /usr/src/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_link-preview-js@3.0.12_encoding@0.1.13__qrcode-terminal@0.12.0/node_modules/@whiskeysockets/baileys/lib/Socket/messages-recv.js:576:33\n    at async /usr/src/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_link-preview-js@3.0.12_encoding@0.1.13__qrcode-terminal@0.12.0/node_modules/@whiskeysockets/baileys/lib/Utils/make-mutex.js:18:36\n    at async Promise.all (index 0)","msg":"failed to sync state from version"}`

**Comment by Luisotee** [comment]
Use the v2-wwjs branch, it uses more ram but is more stable
